### PR TITLE
Adds rarity mechanism.

### PR DESCRIPTION
**Pull request by grantreighard**

### CODE REVIEW

**Comment by grantreighard** [comment]
This is just for your consideration. People have been asking about how to make layers rare, and this adds the ability to tell the program the number of total images and blanks a layer should have. Instead of picking an element directly, this will select a random number and pick an element if it matches the random number.

For example, if you have 3 eye lid tops and set the layer number to 100, 3 times out of 100 you will get an eye lid top and 97 times you will get nothing.

Set the number to the number of elements (3 eye lid tops, the number should be 3) if you want to have 100% chance of getting an actual image for that layer.

**Comment by grantreighard** [comment]
I will also mention that this is a more elegant solution than my workaround for adding rarity, which was to create 99 transparent images and 1 image with content in a folder to make the one with content super rare. This method worked, but with the downside of always having that attribute listed, even if the layer was blank. (e.g. "top eye lid" attribute would have a value of "blank13" if the 13th blank was chosen).

**Comment by gaviigotyou** [comment]
> I will also mention that this is a more elegant solution than my workaround for adding rarity, which was to create 99 transparent images and 1 image with content in a folder to make the one with content super rare. This method worked, but with the downside of always having that attribute listed, even if the layer was blank. (e.g. "top eye lid" attribute would have a value of "blank13" if the 13th blank was chosen).

hahahaha took me a minute to understand what you said but yes. That seems to be the only solution for us none coders. Its a but sad I have to use it this way lol

**Comment by FrostyWasTaken** [comment]
> This is just for your consideration. People have been asking about how to make layers rare, and this adds the ability to tell the program the number of total images and blanks a layer should have. Instead of picking an element directly, this will select a random number and pick an element if it matches the random number.
> 
> For example, if you have 3 eye lid tops and set the layer number to 100, 3 times out of 100 you will get an eye lid top and 97 times you will get nothing.
> 
> Set the number to the number of elements (3 eye lid tops, the number should be 3) if you want to have 100% chance of getting an actual image for that layer.

What if you have more than 1 trait.
If you have a red eye lid and a green eye lid and set them both to 3 and the layer to 100 will you have 3 of each and the rest will be empty? Also is there a chance it can get both red and green eye lids?

**Comment by grantreighard** [comment]
> What if you have more than 1 trait.
> If you have a red eye lid and a green eye lid and set them both to 3 and the layer to 100 will you have 3 of each and the rest will be empty? Also is there a chance it can get both red and green eye lids?

You don't set numbers to images, only layers. So the "eye lid" layer can be set to 100 and if you have 2 images in that folder, they will each have a rarity of (on average) 1/100. Getting any image has a probability of 2/100.

**Comment by FrostyWasTaken** [comment]
Oh I'm looking for a rarity system where I can assign a rarity to each trait. Thanks for the help though

**Pull request merged**
