### PR TITLE
Feature/refactor

### PR DESCRIPTION
**Pull request by philcon93**
I did a bit of a refactor to make the repo follow a few front-end best practices.

- index.js is just the one function that is run, for readable,
- source code moved into `src` directory,
- output code is built in the `build` directory, in which all its file are now gitignored,
- config.js has just the configurable constants e.g layers order, size format, rarity, and default edition amount,
- All the logic is in `main.js`, removed the large layers duplicated array in favorite for a functional way of doing it with the `layersSetup` function.
- Updated `readme` to include an Installation and Usage section, and an image to show a collection of generated images.
- Updated package.json to have 'build' script so you can just run `npm run build` now. You can still pass parameters e.g `npm run build -- 10`, but you can also just update the config file.

I only saw your work yesterday and was so amazed by what you have created, this is awesome! I'm so keen to create some collections with this :)

### CODE REVIEW

**Comment by philcon93** [comment]
Code can be found on: https://github.com/philcon93/generative-art-node/tree/feature/refactor

If you want to test out to make sure nothing has functionality changed.

**Comment by philcon93** [comment]
Should this PR be on the other repo `generative-art-opensource`? I only just saw your youtube videos and noticed you started a different repo, but this one has more exposure and github stars?

**Comment by bperin** [comment]
great addition!

**Comment by Rizzeol** [comment]
Great work @philcon93. Reviewed and looks good !

**Pull request merged**
